---
- name: Install HA-Proxy
  apt:
    name: haproxy
    state: present
    update_cache: true

- name: Setup HA-Proxy configuration
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_config_file }}"
    owner: "{{ user_login }}"
    group: "{{ user_group }}"
    mode: '0644'
  notify: Restart HA-Proxy

- name: Check Grafana service status
  systemd:
    name: haproxy
    enabled: true
    state: started
  register: service_status
  check_mode: true
  changed_when: false
