---
- name: Create user group
  group:
    name: '{{ user_group }}'
    system: yes
    state: present

- name: Create exporter user
  user:
    name: '{{ user_login }}'
    group: '{{ user_group }}'
    system: yes
    create_home: no

- name: Download node exporter archive
  get_url:
    url: "{{ node_exporter_download_url }}"
    dest: /tmp/node_exporter.tar.gz

- name: Extract node exporter archive
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: yes
    owner: '{{ user_login }}'
    group: '{{ user_group }}'
    mode: '0755'
    list_files: yes
  register: node_exporter_extracted

- name: Move node exporter binary files
  copy:
    src: "{{ node_exporter_extracted.dest }}/{{ item }}"
    dest: "/usr/local/bin/{{ item | basename }}"
    remote_src: yes
    owner: '{{ user_login }}'
    group: '{{ user_group }}'
    mode: '0755'
  when: item is match('.*node_exporter$')
  with_items: "{{ node_exporter_extracted.files }}"
  
- name: Create node exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: "{{ node_exporter_service_file }}"
    owner: root
    group: root
    mode: '0644'

- name: Start node exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes

- name: Check Node-Exporter service status
  service:
    name: node_exporter
    state: started
    enabled: true
  check_mode: yes
  changed_when: false
