---
- name: Update packages
  apt:
    update_cache: yes

- name: Add Grafana APT key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    enabled: yes
    state: started
    daemon_reload: yes

- name: Setup Grafana configuration
  template:
    src: grafana.ini.j2
    dest: "{{ grafana_config_file }}"
    owner: "{{ user_login }}"
    group: "{{ user_group }}"
    mode: '0644'
  notify: Restart Grafana

- name: Setup Grafana datasource
  template:
    src: datasources.yaml.j2
    dest: "{{ grafana_datasource_file }}"
    owner: "{{ user_login }}"
    group: "{{ user_group }}"
    mode: '0644'
  notify: Restart Grafana

- name: Setup Grafana dashboards config
  template:
    src: dashboards.yaml.j2
    dest: "{{ grafana_dashboards_file }}"
    owner: "{{ user_login }}"
    group: "{{ user_group }}"
    mode: '0644'
  notify: Restart Grafana

- name: Create dashboards directory
  file:
    path: "{{ grafana_dashboards_dir }}"
    state: directory
    owner: "{{ user_login }}"
    group: "{{ user_group }}"
    mode: '0755'

- name: Download grafana dashboards
  get_url:
    url: "{{ item.url }}"
    dest: "{{ grafana_dashboards_dir }}/{{ item.name }}"
    owner: "{{ user_login }}"
    group: "{{ user_group }}"
    mode: '0644'
  with_items: "{{ dashboards }}"
  notify: Restart Grafana

- name: Check Grafana service status
  service:
    name: grafana-server
    enabled: true
    state: started
  register: service_status
  check_mode: true
  changed_when: false
