- name: Setup master DB
  hosts: beta
  vars:
    mysql_db_id: 1
  roles:
    - mysql-common
    - mysql-init-db
  tags:
    - master
    - db

- name: Setup WordPress
  hosts: alpha
  roles:
    - apache
    - wordpress
  tags:
    - web
    - wordpress
