- name: Prepare Environment
  hosts: all
  become: true
  tasks:
    - name: Install Apache
      package:
        name: apache2
        state: present
    - name: Start Apache
      service:
        name: apache2
        state: started