- name: Setup master DB
  hosts: db-master
  become: true
  vars:
    db_id: 1
    db_user: practicum
    db_name: practicum
    db_password: password
  roles:
    - mysql-common
    - mysql-master

- name: Setup WordPress
  hosts: web
  become: true
  vars:
    db_port: 3306
    db_user: practicum
    db_name: practicum
    db_host: 192.168.56.19
    db_password: password
  roles:
    - wordpress
