- name: Create MySQL user
  mysql_user:
    login_user: "{{ db_root_user }}"
    login_host: "{{ db_host }}"
    login_port: "{{ db_port }}"
    login_unix_socket: "{{ db_login_unix_socket}}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    state: present
    host: "%"
    priv: "{{ db_name }}.*:ALL"

- name: Create database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    login_host: "{{ db_host }}"
    login_port: "{{ db_port }}"

- name: Create replication user
  mysql_user:
    name: "{{ repl_user }}"
    password: "{{ repl_password }}"
    host: '%'
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_user: "{{ db_root_user }}"
    login_host: "{{ db_host }}"
    login_port: "{{ db_port }}"
    login_unix_socket: "{{ db_login_unix_socket}}"

- name: Update binary log
  lineinfile:
    path: "{{ configuration_file }}"
    regexp: '^log_bin'
    line: 'log_bin = /var/log/mysql/mysql-bin.log'
    state: present
  notify: Restart MySQL

