---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ dependencies }}"

- name: Create mysql configuration file
  template:
    src: mysqld.cnf.j2
    dest: "{{ mysql_config_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: Restart MySQL

- name: Enable MySQL
  systemd:
    name: mysql
    enabled: yes
    state: started

- name: Check MySQL service status
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
  check_mode: yes
  changed_when: false
