- name: Prepare database VM
  hosts: db    
  become: true
  vars:
    db_password: rootpassword
    db_user: root
    db_name: practicum

  tasks:
    - name: Install dependencies
      apt:
        name:
          - python3-pymysql
          - mysql-server
        state: present
        update_cache: yes

    - name: Start MySQL
      service:
        name: mysql
        state: started

    - name: Set MySQL root password (if not already set)
      mysql_user:
        name: '{{ db_user }}'
        password: '{{ db_password }}'
        login_unix_socket: /var/run/mysqld/mysqld.sock
        host: localhost
        state: present

    - name: Create database
      mysql_db:
        name: '{{ db_name }}'
        state: present
        login_user: '{{ db_user }}'
        login_password: '{{ db_password }}'
