- name: Prepare web VM
  hosts: web
  become: true
  tasks:
    - name: Install Dependencies
      apt:
        name:
          - apache2
          - mysql-client
          - php
          - php-mysql
          - php-cli
          - php-curl
          - php-gd
          - php-intl
          - php-mbstring
          - php-xml
          - php-zip
        state: present
        update_cache: yes

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        copy: no

    - name: Set permissions for WordPress
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        recurse: yes

    - name: Update WordPress configuration
      copy: 
        src: wp-config.php
        dest: /var/www/html/wordpress/wp-config.php
        owner: www-data
        group: www-data
        mode: '0644'
    
    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes
